# Generated by Django 6.0.3 on 2026-03-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы рейтинга'),
        ),
    ]
