# Generated by Django 6.0.3 on 2026-03-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usual_rewards',
            field=models.TextField(blank=True, verbose_name='Типичные призы'),
        ),
    ]
