# Generated by Django 6.0.3 on 2026-03-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Направление деятельности'),
        ),
        migrations.AddField(
            model_name='user',
            name='trust_rating',
            field=models.FloatField(default=5.0, verbose_name='Рейтинг доверия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'Участник'), ('organizer', 'Организатор'), ('inspector', 'Инспектор')], default='participant', max_length=20, verbose_name='Роль'),
        ),
    ]
