# Generated by Django 6.0.3 on 2026-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_direction_user_trust_rating_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points_it',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы: IT'),
        ),
        migrations.AddField(
            model_name='user',
            name='points_media',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы: Медиа'),
        ),
        migrations.AddField(
            model_name='user',
            name='points_project',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы: Проекты'),
        ),
        migrations.AddField(
            model_name='user',
            name='points_social',
            field=models.PositiveIntegerField(default=0, verbose_name='Баллы: Социальное'),
        ),
    ]
