# Generated by Django 6.0.3 on 2026-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мероприятия')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата и время проведения')),
                ('location', models.CharField(max_length=255, verbose_name='Место проведения')),
                ('reward_points', models.PositiveIntegerField(default=10, verbose_name='Баллы за участие')),
                ('event_type', models.CharField(choices=[('it', 'IT'), ('social', 'Социальное'), ('project', 'Проектная деятельность'), ('media', 'Медиа')], default='it', max_length=20, verbose_name='Тип мероприятия')),
                ('bonus_info', models.CharField(blank=True, max_length=255, verbose_name='Дополнительные бонусы (мерч и т.д.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Актуально')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Присутствие подтверждено')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Запись на мероприятие',
                'verbose_name_plural': 'Записи на мероприятия',
            },
        ),
    ]
