# Generated by Django 6.0.3 on 2026-03-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bonus_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Дополнительный бонус (мерч, билеты)'),
        ),
    ]
