# Generated by Django 6.0.3 on 2026-03-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_bonus_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='points_award',
            new_name='reward_points',
        ),
    ]
