# Generated by Django 6.0.3 on 2026-03-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='reward_points',
            new_name='points',
        ),
    ]
