# Generated by Django 6.0.3 on 2026-03-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_points_award_event_reward_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bonus_type',
        ),
    ]
