# Generated by Django 6.0.3 on 2026-03-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_bonus_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='status',
            new_name='is_confirmed',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('it', 'IT'), ('social', 'Социальное'), ('project', 'Проектная деятельность'), ('media', 'Медиа')], default='it', max_length=20, verbose_name='Тип мероприятия'),
        ),
    ]
