# Generated by Django 6.0.3 on 2026-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Количество баллов')),
                ('description', models.CharField(max_length=255, verbose_name='Описание операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начисления')),
            ],
            options={
                'verbose_name': 'История баллов',
                'verbose_name_plural': 'История баллов',
                'ordering': ['-created_at'],
            },
        ),
    ]
